### ISSUE TITLE
CI/CD for deployments.

### ISSUE THREAD

**Issue by dylanbstorey** [andrewm4894/airflow-provider-anomaly-detection#6]
You want any help getting this set up for when you release ?

**Comment by andrewm4894** [comment]
Hey, yeah that would be cool.

Actually need to add some testing too lol

**Comment by dylanbstorey** [comment]
https://github.com/andrewm4894/airflow-provider-anomaly-detection/pull/7 

for your review. 

Need to add your pypi api token in as a github actions secret before you distribute but should be gtg otherwise.
